id: AD41D184B
title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
  Khyentse, Thupten Chökyi Gyatso
type: translation
pechas:
- I263E58BF
- I9A3EEA4B
- IAA50FDAF
- I67ACB4CF
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:45.254330
  last_modified_at: 2023-01-04 11:50:45.254343
  collections:
  - Dzongsar Khyentse Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I263E58BF/0577: C0B5
  I9A3EEA4B/7D07: C0B5
  IAA50FDAF/DD32: C0B5
  I67ACB4CF/574B: C0B5
